agents:
  trae_agent:
    enable_lakeview: true
    model: trae_agent_model
    max_steps: 200
    tools:
      - bash
      - str_replace_based_edit_tool
      - sequentialthinking
      - task_done
allow_mcp_servers:
  - playwright
# mcp_servers:
#   playwright:
#     command: npx
#     args:
#       - '@playwright/mcp@0.0.27'
lakeview:
  model: lakeview_model

model_providers:
  doubao:
    api_key: your_anthropic_api_key
    provider: anthropic

models:
  trae_agent_model:
    model_provider: doubao
    model: claude-4-sonnet
    parallel_tool_calls: true
  lakeview_model:
    model_provider: doubao
    model: claude-3.5-sonnet
