version: '3.8'

services:
  agent-server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: agent-server
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    ports:
      - '8000:8000'
    volumes:
      - ./trae-agent/trae_config.yaml:/app/trae-agent/trae_config.yaml
    networks:
      - agent-network
    # run target agent
    command: ['uv', 'run', 'python', '-m', 'trae-agent.main']

networks:
  agent-network:
    driver: bridge
